"""change type_of_business to string

Revision ID: 0857a2983f11
Revises: dbdae2e00ba7
Create Date: 2026-04-13 17:59:05.568318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0857a2983f11'
down_revision = 'dbdae2e00ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.alter_column('type_of_business',
               existing_type=postgresql.ENUM('Agriculture', 'Construction', 'Manufacturing', 'Wholesale', 'Transportation', name='businesstype'),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.alter_column('type_of_business',
               existing_type=sa.String(length=120),
               type_=postgresql.ENUM('Agriculture', 'Construction', 'Manufacturing', 'Wholesale', 'Transportation', name='businesstype'),
               existing_nullable=False)

    # ### end Alembic commands ###
