"""add business_id to user

Revision ID: 372dd7b95c8d
Revises: 0857a2983f11
Create Date: 2026-04-13 19:10:48.353594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372dd7b95c8d'
down_revision = '0857a2983f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'business', ['business_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###
