"""add business_description to business

Revision ID: dbdae2e00ba7
Revises: f0ef37b53184
Create Date: 2026-04-13 15:39:40.159599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdae2e00ba7'
down_revision = 'f0ef37b53184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_description', sa.String(length=255), nullable=False))

    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage_rate', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.drop_column('percentage_rate')

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('business_description')

    # ### end Alembic commands ###
