"""added contact messages table

Revision ID: e7dda52657cd
Revises: f0ef37b53184
Create Date: 2026-04-13 22:34:41.664272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7dda52657cd'
down_revision = 'f0ef37b53184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage_rate', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.drop_column('percentage_rate')

    op.drop_table('contact_messages')
    # ### end Alembic commands ###
