"""empty message

Revision ID: f0ef37b53184
Revises: 0763d677d453
Create Date: 2026-04-06 23:29:53.063296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ef37b53184'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_business', sa.Enum('Agriculture', 'Construction', 'Manufacturing', 'Wholesale', 'Transportation', name='businesstype'), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('business_phone_number', sa.String(length=120), nullable=False),
    sa.Column('business_address', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discount')
    op.drop_table('business')
    # ### end Alembic commands ###
